### ISSUE TITLE
Road map 

### ISSUE THREAD

**Issue by bioworkflows** [bioworkflows/bioworkflows-help#7]
- [ ] Start project
- [ ] Workflow (basic properties)
- [ ] Add/update/delete workflow 
- [ ] List and view workflow
- [ ] Conversion of workflows to HTML
- [ ] Display of resulting workflow
- [ ] Homepage
- [ ] Initial deployment
- [ ] Publish and approval process (auto approval at first)
- [ ] Premium user account
- [ ] User group (organization) etc
- [ ] Premium group account (organization)
- [ ] Comment
- [ ] Rating
